### ISSUE TITLE
Test failure with gnome-keyring on Ubuntu Xenial

### ISSUE THREAD

**Issue by wrouesnel** [tmc/keyring#11]
From the current master:
```
$ go test github.com/tmc/keyring
Get() error: No such interface 'org.freedesktop.Secret.Collection' on object at path /org/freedesktop/secrets/collection/Default
--- FAIL: TestBasicSetGet (0.00s)
	keyring_test.go:20: Set() error: keyring/dbus: CreateItem error: No such interface 'org.freedesktop.Secret.Collection' on object at path /org/freedesktop/secrets/collection/Default
	keyring_test.go:24: Get() error: No such interface 'org.freedesktop.Secret.Collection' on object at path /org/freedesktop/secrets/collection/Default
FAIL
FAIL	github.com/tmc/keyring	0.009s
```

The problem seems to be that by default, the plugin is looking for a password collection called "Default" rather then looking at which password chain _is_ the default (on my system it defaults to being named "Login").

**Comment by hai-ld** [comment]
@wrouesnel Have you found any workaround this issue? I'm setting up Netflix-Skunkworks/go-jira on Xenial and encounter this exact issue.

**Comment by hai-ld** [comment]
Nevermind, I figured it out. Just open keyring manager (seahorse on GNOME 3) and create a new _Password keyring_ named "Default".

**Comment by bartlibert** [comment]
There seems to be a (non-perfect) solution here, too bad it seems a bit abandoned: https://github.com/acsellers/keyring/commit/d629033c36dc784cb8d2b03da042ab576bc1efa3

**Comment by tmc** [comment]
I'm open to a patch here.
