### ISSUE TITLE
[Windows] Rely on the credentials API for Windows

### ISSUE THREAD

**Issue by rgbkrk** [tmc/keyring#8]
[Credentials API](https://msdn.microsoft.com/en-us/library/aa374731%28v=VS.85%29.aspx#credentials_management_functions)

Alternatively, there's also [`CredReadW` within the Win32 API](https://msdn.microsoft.com/en-us/library/windows/desktop/aa374804%28v=vs.85%29.aspx).

I'm not a Windows dev, but it would be nice to abstract this in the same way as [the Python keyring library does it](https://bitbucket.org/kang/python-keyring-lib/src/b2e88501a6a9bc7f1c7c230a6431ac0860ff4e50/keyring/backends/Windows.py?at=default).

**Comment by tmc** [comment]
@rgbkrk I think that would be great. I'm also not a windows developer but would love contribution here.

**Comment by allcloud-jonathan** [comment]
@tmc would it be feasible to use a sub library for that? In an other project I've been using 
github.com/danieljoos/wincred

**Comment by tmc** [comment]
@allcloud-jonathan yes I think so, I haven't had time to take a very close look, do you recommend that library?

**Comment by sucotronic** [comment]
Another alternative to using a library will be using the shell: https://stackoverflow.com/questions/9221245/how-do-i-store-and-retrieve-credentials-from-the-windows-vault-credential-manage

**Comment by tmc** [comment]
I merged recent contributions to use wincred.
