### ISSUE TITLE
Interest in consolidating efforts?

### ISSUE THREAD

**Issue by lox** [tmc/keyring#9]
I've been working on a fairly similar library for [aws-vault](https://github.com/99designs/aws-vault):

https://github.com/99designs/aws-vault/tree/master/keyring

It includes:
- Get, Set, Remove and Keys (list) in the interface
- Multiple provider support, where the caller can specify a preference
- Implementations using cgo for OSX/Keychain and Linux/KWallet

My plan is to add support for `libsecret` and something windows related. Thoughts on targeting this at keyring 2.0?

**Comment by tmc** [comment]
I'd love to see libsecret and windows contributions.

**Comment by lox** [comment]
Btw, there is now https://github.com/99designs/keyring.

**Comment by tmc** [comment]
I'm happy to distribute commit bits after someone has contributed. Closing for now.

**Comment by lox** [comment]
Sorry for the lack of follow up @tmc. Will consider for the future, at this stage I think I'd like to keep it under the 99designs org.
